spring:
  application:
    name: cadabra-giftcard-winner
  main:
    banner-mode: off
  profiles:
    default: local

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true


user:
  chunk-size: 10

csv:
  purchases:
    default-path: data/purchases.csv
    columns: userId,amount
    delimiter: ","
    lines-to-skip: 1
    max-skip-lines: 5
    chunk-size: 10

winner:
  min-purchase-amount: 20

integration:
  user-api:
    url: ${USER_API_URL:https://jsonplaceholder.typicode.com/users}
